version: "3.7"
services:
  pocs-camera:
    container_name: pocs-camera
    hostname: pocs-camera
    image: "${IMAGE_NAME:-gcr.io/panoptes-exp/panoptes-camera}:${TAG_NAME:-gphoto}"
    build:
      context: ../
      dockerfile: ./Dockerfile
    restart: on-failure
    init: true
    privileged: true
    ports:
      - "8000:8000"
    volumes:
      - ${PANDIR:-.}/images:/images
