services:
  camera-service:
    image: "${IMAGE_NAME:-gcr.io/panoptes-exp/pocs-camera}:${TAG_NAME:-latest}"
    build:
      context: ../
      dockerfile: ./Dockerfile
    init: true
    tty: true
    container_name: camera-service
    privileged: true
    port:
      - 6565:6565
    restart: on-failure
    volumes:
      - $PWD/images:/images
